# Changing the port for the GraphQL server
server:
  port: 8180


#spring:
#  security:
#    oauth2:
#      resourceserver:
#        opaque:
#          introspection-uri: http://localhost:8180/simulated_oauth_authorization_server/token/introspect
#          introspection-client-id: barClient
#          introspection-client-secret: barClientSecret
#